# Generated by Django 3.1.2 on 2021-06-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspoint',
            name='link',
        ),
        migrations.AddField(
            model_name='newspoint',
            name='desc',
            field=models.CharField(default='covid', max_length=300),
        ),
    ]
