# Generated by Django 3.1.2 on 2021-06-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210609_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspoint',
            name='desc',
            field=models.URLField(default='covid', max_length=300),
        ),
    ]
